import './globals.css'
import type { Metadata } from 'next'
import SessionDataContextLayout from './auth/login/@SessionContextProvider/layout'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-inter">
        <SessionDataContextLayout>
          {children}
        </SessionDataContextLayout>
      </body>
    </html>
  )
}
