import './globals.css'
import type { Metadata } from 'next'
import SessionDataContextLayout from './auth/login/@SessionContextProvider/layout'
import SrchPostsTmpDirUserImagesContextProviderLayout from './home/@srchPostsTmpDirUserImagesContextProvider/layout'
import SrchPostsTmpDirFiguresContextProviderLayout from './home/@srchPostsTmpDirFiguresContextProvider/layout'
import SrchPostsCommentsTmpDirUserImagesContextProviderLayout from './home/@srchPostsCommentsTmpDirUserImagesContextProvider/layout'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-inter">
        <SessionDataContextLayout>
          <SrchPostsTmpDirUserImagesContextProviderLayout>
            <SrchPostsTmpDirFiguresContextProviderLayout>
              <SrchPostsCommentsTmpDirUserImagesContextProviderLayout>
                {children}
              </SrchPostsCommentsTmpDirUserImagesContextProviderLayout>
            </SrchPostsTmpDirFiguresContextProviderLayout>
          </SrchPostsTmpDirUserImagesContextProviderLayout>
        </SessionDataContextLayout>
      </body>
    </html>
  )
}
